name: Java Maven Docker
on:
  workflow_dispatch:
    branches: [master]
  push:
    branches: [master]

env:
  image_path: ${{ github.repository }}
  image_name: golang-docker-test

jobs:
  build:
    runs-on: [ubuntu]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set container registry env
        run: |
          echo "registry=docker.$(echo $GITHUB_SERVER_URL | cut -c 9-)" >> $GITHUB_ENV
        shell: bash

      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
          check-latest: true

      - name: Test  application
        run: go test -v ./tests/...

      - name: Build docker image for the application
        run: docker build --rm -t ${{env.registry}}/${{env.image_path}}/${{env.image_name}}:latest .

      - name: Log on to github docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub packages
        run: docker push ${{env.registry}}/${{env.image_path}}/${{env.image_name}}:latest

      - name: Remove the docker image from container registry
        uses: actions/delete-package-versions@v2
        with:
          package-name: "${{env.image_name}}"
